Repository postmanlabs/postman-collection, pull requests merged in 2018-06, with the labels that each got.

#656 chore(package): update parse-gitignore to version 0.5.1
  package.json
Labels: greenkeeper

#652 Content info module
  CHANGELOG.md
  lib/collection/response.js
  lib/content-info/index.js
  test/unit/content-info.test.js
  test/unit/response.test.js
Labels: enhancement

#663 JSDoc: Fix `Description~definition` property
  lib/collection/description.js
Labels: documentation

#666 Added support for mutation tracking in VariableScope
  lib/collection/mutation-tracker.js
  lib/collection/variable-scope.js
  lib/index.js
  test/system/source-modules.test.js
  test/unit/mutation-tracker.test.js
  test/unit/variable-scope.test.js
Labels: enhancement

#668 Improve documentation and type safety checks to mutation tracker and variable scopes
  lib/collection/mutation-tracker.js
  lib/collection/variable-scope.js
  test/unit/mutation-tracker.test.js
Labels: documentation, tests

#669 Fixed JSDoc in VariableScope [ci skip]
  lib/collection/variable-scope.js
Labels: documentation

#670 Remove console warn statement in variable scope
  .eslintrc
  lib/collection/variable-scope.js
  npm/.eslintrc
Labels: bug

#672 Fix documentation for auth type in item group and collection
  lib/collection/collection.js
  lib/collection/item-group.js
Labels: documentation

#674 Support for utility function to extract JSON from json response
  CHANGELOG.md
  lib/collection/response.js
  test/unit/response.test.js
Labels: enhancement
