Repository postmanlabs/postman-collection, pull requests merged in 2018-12, with the labels that each got.

#743 Inherit protocolProfileBehavior from parent
  examples/collection-v2.json
  lib/collection/item-group.js
  lib/collection/item.js
  test/unit/item-group.test.js
  test/unit/item.test.js
Labels: enhancement

#752 Greenkeeper/eslint plugin jsdoc 3.12.0
  package-lock.json
  package.json
Labels: greenkeeper

#755 Greenkeeper/eslint plugin jsdoc 3.14.0
  package-lock.json
  package.json
Labels: greenkeeper

#763 Fix variable string substitutions
  lib/superstring/index.js
  test/unit/property.test.js
Labels: bug
