Repository postmanlabs/postman-collection, pull requests merged in 2018-03, with the labels that each got.

#589 Collection~toJSON description fix
  lib/collection/collection.js
  test/unit/collection.test.js
Labels: bug, discourse

#603 chore(package): update mocha to version 5.0.4
  package.json
Labels: greenkeeper

#607 Request body sanity fix
  lib/collection/request-body.js
  test/unit/request-body.test.js
Labels: bug

#609 chore(package): update eslint-plugin-lodash to version 2.7.0
  package.json
Labels: greenkeeper

#612 Update marked
  lib/collection/description.js
  package.json
Labels: enhancement
